name: flutter_gehry
description: A Flutter package that provides a way to easily do a responsive layout, using breakpoints.
version: 1.4.0
homepage: https://github.com/Jtplouffe/flutter_gehry
repository: https://github.com/Jtplouffe/flutter_gehry
platforms:
  android:
  ios:
  linux:
  macos:
  web:
  windows:

environment:
  sdk: ">=2.17.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
